#!/usr/bin/env bash
set -euo pipefail

die() { printf 'error: %s\n' "$*" >&2; exit 1; }
log() { printf '%s\n' "$*" >&2; }

PLUGINS_FILE="${PLUGINS_FILE:-plugins.yaml}"
# Machine-readable registry generated by coreruleset/plugin-registry from its
# registry.yaml (schema: registry-schema.json in the same repository).
REGISTRY_URL="${REGISTRY_URL:-https://raw.githubusercontent.com/coreruleset/plugin-registry/main/registry.json}"
REGISTRY_SCHEMA_VERSION=1
GITHUB_API="${GITHUB_API:-https://api.github.com}"

command -v yq >/dev/null || die "yq not found"
command -v jq >/dev/null || die "jq not found"
command -v curl >/dev/null || die "curl not found"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

[ -f "$PLUGINS_FILE" ] || die "${PLUGINS_FILE} not found"

gh_get() {
  curl -fsSL \
    -H "Accept: application/vnd.github+json" \
    ${GITHUB_TOKEN:+-H "Authorization: Bearer ${GITHUB_TOKEN}"} \
    "${GITHUB_API}/$1" 2>/dev/null || true
}

# --- 1. Fetch + parse registry -------------------------------------------
log "fetching registry: ${REGISTRY_URL}"
curl -fsSL "$REGISTRY_URL" >"${tmp}/registry.json" \
  || die "registry fetch failed (no partial changes written)"
jq -e . "${tmp}/registry.json" >/dev/null 2>&1 \
  || die "registry is not valid JSON (no partial changes written)"

# Fail closed on a schema we have not reviewed: a new major could rename or
# re-scope the fields this script keys on (repository, status, private).
schema_version="$(jq -r '.schema_version // empty' "${tmp}/registry.json")"
[ "$schema_version" = "$REGISTRY_SCHEMA_VERSION" ] \
  || die "unsupported registry schema_version '${schema_version}' (expected ${REGISTRY_SCHEMA_VERSION})"

# Keep every registered plugin except drafts and private repositories: a draft
# has no reviewed rule content yet, and a private repository cannot be fetched
# by the build. Only GitHub repositories are registered today (enforced by the
# registry schema), so the slug is the URL path.
jq -r '.plugins[]
  | select(.status != "draft" and (.private // false) != true)
  | .repository
  | sub("^https://github\\.com/"; "")
  | sub("/$"; "")' "${tmp}/registry.json" \
  | LC_ALL=C sort -u >"${tmp}/slugs.txt"
[ -s "${tmp}/slugs.txt" ] || die "registry parse produced no slugs"

# --- 2. Reconcile registry slugs -----------------------------------------
present="$(yq -o=json -I=0 '[.plugins[].repo]' "$PLUGINS_FILE")"
managed="$(yq -o=json -I=0 \
  '[.plugins[] | select(.origin == "registry" and .disabled != true) | .repo]' \
  "$PLUGINS_FILE")"
slugs="$(jq -R -s 'split("\n") | map(select(length > 0))' "${tmp}/slugs.txt")"

# Additions: registry slugs with no entry at all.
jq -rn --argjson present "$present" --argjson slugs "$slugs" \
  '$slugs[] | select(. as $s | ($present | index($s)) | not)' \
  | while IFS= read -r slug; do
      [ -z "$slug" ] && continue
      log "adding registry plugin ${slug}"
      yq -i ".plugins += [{\"repo\": \"${slug}\", \"origin\": \"registry\", \"pin\": null, \"dir\": null, \"disabled\": false, \"resolved\": null}]" \
        "$PLUGINS_FILE"
    done

# Removals: managed registry entries no longer in the registry.
jq -rn --argjson managed "$managed" --argjson slugs "$slugs" \
  '$managed[] | select(. as $m | ($slugs | index($m)) | not)' \
  | while IFS= read -r slug; do
      [ -z "$slug" ] && continue
      log "removing dropped registry plugin ${slug}"
      yq -i "del(.plugins[] | select(.repo == \"${slug}\"))" "$PLUGINS_FILE"
    done

# --- 3. Resolve versions for every non-disabled entry --------------------
count="$(yq '.plugins | length' "$PLUGINS_FILE")"
for i in $(seq 0 $((count - 1))); do
  [ "$(yq ".plugins[$i].disabled" "$PLUGINS_FILE")" = "true" ] && continue
  repo="$(yq ".plugins[$i].repo" "$PLUGINS_FILE")"
  pin="$(yq ".plugins[$i].pin" "$PLUGINS_FILE")"

  if [ -n "$pin" ] && [ "$pin" != "null" ]; then
    ver="${pin:0:7}"; rtype="sha"; sha="$pin"
  else
    rel="$(gh_get "repos/${repo}/releases/latest")"
    tag="$(printf '%s' "$rel" | jq -r 'if .tag_name then (.tag_name | sub("^v"; "")) else "" end')"
    if [ -n "$tag" ]; then
      refj="$(gh_get "repos/${repo}/git/refs/tags/v${tag}")"
      sha="$(printf '%s' "$refj" | jq -r '.object.sha // empty')"
      [ -z "$sha" ] && {
        refj="$(gh_get "repos/${repo}/git/refs/tags/${tag}")"
        sha="$(printf '%s' "$refj" | jq -r '.object.sha // empty')"
      }
      [ -n "$sha" ] || die "could not resolve tag ${tag} for ${repo}"
      ver="$tag"; rtype="tag"
    else
      headj="$(gh_get "repos/${repo}/commits/HEAD")"
      sha="$(printf '%s' "$headj" | jq -r '.sha // empty')"
      [ -n "$sha" ] || die "could not resolve HEAD for ${repo}"
      ver="${sha:0:7}"; rtype="sha"
    fi
  fi

  log "resolved ${repo} -> ${ver} (${rtype}) ${sha}"
  yq -i ".plugins[$i].resolved = {\"version\": \"${ver}\", \"ref_type\": \"${rtype}\", \"commit_sha\": \"${sha}\"}" \
    "$PLUGINS_FILE"
done

log "sync complete; plugins.yaml updated in place"
